#index:
#    path: /
#    controller: App\Controller\DefaultController::index
main:
    path: /
    controller: App\Controller\main::main
log_in:
    path: /log_in
    controller: App\Controller\log_in::log_in
sign_up:
    path: /sign_up
    controller: App\Controller\sign_in:sign_up
